version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes: ['./assets:/assets', './mysql:/var/lib/mysql']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user fills out
      MYSQL_USER: user fills out
      MYSQL_PASSWORD: user fills out
    networks:
      - wpsite

  # phpmyadmin:
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite

  # Wordpress
  wordpress:
    container_name: wp
    depends_on:
      - db
    image: wordpress
    ports:
      - '80:80'
      - '9003:9003'
    restart: always
    volumes: ['./wp:/var/www/html/']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: user fills out
      WORDPRESS_DB_USER: user fills out
      WORDPRESS_DB_PASSWORD: user fills out
    networks:
      - wpsite
networks:
  wpsite: